views:
  - title: Main
    cards:
      - type: grid
        title: Test Grid Square
        square: true
        columns: 2
        cards:
          - type: custom:apexcharts-card
            stacked: true
            series:
              - entity: sensor.random_0_1000
                name: test1
                type: area
                curve: straight
              - entity: sensor.random_0_1000
                name: test2
                type: area
            hours_to_show: 0.20
            cache: true
            layout: minimal
            header:
              show: false
          - type: custom:apexcharts-card
            stacked: true
            series:
              - entity: sensor.random_0_1000
                name: test1
                type: bar
              - entity: sensor.random_0_1000
                name: test2
                type: bar
            hours_to_show: 0.25
            cache: true

      - type: custom:apexcharts-card
        stacked: true
        series:
          - entity: sensor.random_0_1000
            name: RAM Usage
            unit: Mb
            type: area
            curve: smooth
          - entity: sensor.random_0_1000
            name: Ram Free
            type: area
        hours_to_show: 0.20
        cache: true
        layout: minimal
        header:
          floating: true


      - type: custom:apexcharts-card
        stacked: false
        series:
          - entity: sensor.random_0_1000
            name: test1
            type: bar
          - entity: sensor.random_0_1000
            name: test2
            type: bar
        hours_to_show: 0.25
        cache: true
      - type: custom:apexcharts-card
        hours_to_show: 200
        series:
          - entity: sensor.humidity
            curve: straight

      - type: custom:apexcharts-card
        hours_to_show: 24
        series:
          - entity: sensor.humidity
            curve: smooth
            type: area
            group_by:
              duration: 5h
              func: avg
