views:
  - title: Main
    cards:
      - type: grid
        title: Test Grid Square
        square: true
        columns: 2
        cards:
          - type: custom:apexcharts-card
            stacked: true
            series:
              - entity: sensor.random_0_1000
                name: test1
                type: area
                curve: straight
              - entity: sensor.random_0_1000
                name: test2
                type: area
            hours_to_show: 0.20
            cache: true
            layout: minimal
            header:
              show: false
          - type: custom:apexcharts-card
            stacked: true
            series:
              - entity: sensor.random_0_1000
                name: test1
                type: bar
              - entity: sensor.random_0_1000
                name: test2
                type: bar
            hours_to_show: 0.25
            cache: true

      - type: custom:apexcharts-card
        stacked: true
        series:
          - entity: sensor.random_0_1000
            name: RAM Usage
            unit: Mb
            type: area
            curve: smooth
          - entity: sensor.random_0_1000
            name: Ram Free
            type: area
        hours_to_show: 0.20
        cache: true
        layout: minimal
        header:
          floating: true


      - type: custom:apexcharts-card
        stacked: false
        series:
          - entity: sensor.random_0_1000
            name: test1
            type: bar
          - entity: sensor.random_0_1000
            name: test2
            type: bar
        hours_to_show: 0.25
        cache: true
      - type: custom:apexcharts-card
        hours_to_show: 200
        series:
          - entity: sensor.humidity
            curve: straight

      - type: custom:apexcharts-card
        hours_to_show: 48
        series:
          - entity: sensor.random0_100
            name: AVG
            curve: smooth
            type: area
            group_by:
              duration: 1h
              func: avg
          - entity: sensor.random0_100
            curve: smooth
            name: MIN
            type: area
            group_by:
              duration: 1h
              func: min
          - entity: sensor.random0_100
            curve: smooth
            name: MAX
            type: area
            group_by:
              duration: 1h
              func: max
          - entity: sensor.random0_100
            curve: smooth
            name: LAST
            type: area
            group_by:
              duration: 3h
              func: last
          - entity: sensor.random0_100
            curve: smooth
            name: FIRST
            type: area
            group_by:
              duration: 3h
              func: first

      - type: custom:apexcharts-card
        series:
          - entity: sensor.humidity
            type: area
            name: Office Humidity
            group_by:
              func: avg
              duration: 1h
          - entity: sensor.random0_100
            type: area
            name: Outside Humidity
            group_by:
              func: avg
              duration: 1h

      - type: custom:apexcharts-card
        header:
          show: false
        series:
          - entity: sensor.humidity
            type: line
            name: Office Humidity
            group_by:
              func: avg
              duration: 1h
          - entity: sensor.random0_100
            type: bar
            name: Outside Humidity
            group_by:
              func: avg
              duration: 1h